[package]
name = "rl_discord_rpc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rl_discord_rpc"
path = "src/main.rs"

[[bin]]
name = "rl_rpc_wrapper"
path = "src/wrapper.rs"

[dependencies]
rlstatsapi = "0.1"
discord-rich-presence = "0.2"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json"] }
urlencoding = "2"